language: python
python:
  - "3.5"
install:
    - travis_retry pip install tox
script:
    - sudo -E tox
notifications:
    email: false
addons:
  postgresql: "9.3"
sudo: true
env:
    - ZGRES_DESTROY_MACHINE=true
