language: python
python:
  - "3.5"
install:
    - travis_retry pip install tox
script:
    - tox
    - sudo -E env "PATH=$PATH" ZGRES_DESTROY_MACHINE=true tox
notifications:
    email: false
addons:
  postgresql: "9.4"
sudo: true
